pipeline {
  agent {
    label 'docker'
  }

  environment {
    GOVERSION = '1.16.2'
    PATH = "${env.WORKSPACE}/go/bin:${env.WORKSPACE}/kind/bin:${env.WORKSPACE}/kubectl/bin:${PATH}"
    K8S_VERSION = 'v1.20.0'
  }

  stages {
    stage('Install tools locally') {
      steps {
        cleanWs()
        sh 'wget -q -O- https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz | tar xz'
        sh '''
        mkdir -p kind/bin
        curl -Lo kind/bin/kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-amd64
        chmod +x kind/bin/kind
        '''
        sh '''
        mkdir -p kubectl/bin
        curl -Lo kubectl/bin/kubectl https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl
        chmod +x kubectl/bin/kubectl
        '''
      }
    }

    stage('Use Kind') {
      steps {
        sh 'kind delete cluster --name test || true'
        sh 'kind create cluster --name test --image kindest/node:${K8S_VERSION} --kubeconfig kubeconfig.${K8S_VERSION}'
        sh 'kubectl cluster-info --context kind-test --kubeconfig kubeconfig.${K8S_VERSION}'
        sh '''
            export KUBECONFIG=kubeconfig.${K8S_VERSION}

            # Install Helm locally
            wget -q -O- https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            # Install Grafana, Loki, etc. using Helm
            helm repo add grafana https://grafana.github.io/helm-charts
            kubectl create namespace logging
            helm upgrade --install loki --namespace=logging grafana/loki-stack \
                --set fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false

            # Wait for deployment to complete
            echo "Waiting for Grafana to start up..."
            until kubectl rollout status -n logging deployment/loki-grafana; do
                echo -n '.'
                sleep 2
            done
            echo "Grafana running"

            kubectl get pods --all-namespaces
        '''
      }
      post {
        always {
            sh 'kind delete cluster --name test'
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}